language: ruby
rvm:
  - "1.9.3"
  - "2.1.2"
  - "2.3"
  - ruby-head
  - rbx-2
  - rbx
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-head
sudo: false
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx
